// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCPi8YP1B0JeBLygfxApLutXlura-FoLQg',
    appId: '1:1035061292381:web:980890b88d8d8104570cb4',
    messagingSenderId: '1035061292381',
    projectId: 'flutfire-auth-tutorial',
    authDomain: 'flutfire-auth-tutorial.firebaseapp.com',
    storageBucket: 'flutfire-auth-tutorial.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAGCBc4dMhl2DBibCQiFUJOzB0Ba-y5kGA',
    appId: '1:1035061292381:android:f9a571a51cbcfa8e570cb4',
    messagingSenderId: '1035061292381',
    projectId: 'flutfire-auth-tutorial',
    storageBucket: 'flutfire-auth-tutorial.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBQq1vpqbx6dqooefqdP0WMRjd0O04beCE',
    appId: '1:1035061292381:ios:8ccd1cbbb7dce6ec570cb4',
    messagingSenderId: '1035061292381',
    projectId: 'flutfire-auth-tutorial',
    storageBucket: 'flutfire-auth-tutorial.appspot.com',
    iosClientId: '1035061292381-mga44o6bv6hqtrcl9j502nee3im1u9q7.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterFireauthTutorial',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBQq1vpqbx6dqooefqdP0WMRjd0O04beCE',
    appId: '1:1035061292381:ios:8ccd1cbbb7dce6ec570cb4',
    messagingSenderId: '1035061292381',
    projectId: 'flutfire-auth-tutorial',
    storageBucket: 'flutfire-auth-tutorial.appspot.com',
    iosClientId: '1035061292381-mga44o6bv6hqtrcl9j502nee3im1u9q7.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterFireauthTutorial',
  );
}
